# Generated by Django 4.2.11 on 2024-12-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
