# Generated by Django 5.1.5 on 2025-01-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_valid_until',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
