steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/django-app:$SHORT_SHA', '.']
    id: Build Docker image

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/django-app:$SHORT_SHA']
    id: Push Docker image

  - name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform
        terraform init
        terraform apply -auto-approve -var "docker_image=gcr.io/$PROJECT_ID/django-app:$SHORT_SHA"
    id: Apply Terraform
