services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: <postgres_pwd>
      POSTGRES_DBNAME: postgres
    ports:
      - "5432:5432"

  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate --noinput && python manage.py seed_db && python manage.py runserver 0.0.0.0:${PORT}"
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres

